version: 2

sources:
  - name: staging
    database: de-zoom-camp-412008
    # For postgres:
    #database: production
    schema: trips_data_all
    # loaded_at_field: record_loaded_at
    tables:
      - name: stg_fhv_tripdata